import React, { useState, useEffect, useCallback, useRef } from "react";
import CardC from "../components/CardC";
import nft_test from "../assets/nft4.jpg";

export const Splitting = () => {
  return (
    <div>
      <h1 className="text-white text-3xl flex mt-7 justify-center">
        Split test
      </h1>
      <div className="flex justify-center">
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5 mt-5 mx-[5%]">
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={10}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={57}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={70}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={10}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={100}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={30}
          />
          <CardC
            img_src={nft_test}
            name={"yo"}
            description={"yooooo"}
            price={2.3}
            is1155={true}
            owned={50}
          />
          <CardC
            img_src={nft_test}
            name={"hahahahaha"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={70}
          />
          <CardC
            img_src={nft_test}
            name={"ooooooooo"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={44}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={10}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={57}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={70}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={10}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={100}
          />
          <CardC
            img_src={nft_test}
            name={"Hello"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={30}
          />
          <CardC
            img_src={nft_test}
            name={"yo"}
            description={"yooooo"}
            price={2.3}
            is1155={true}
            owned={50}
          />
          <CardC
            img_src={nft_test}
            name={"hahahahaha"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={70}
          />
          <CardC
            img_src={nft_test}
            name={"ooooooooo"}
            description={"哈哈哈哈哈"}
            price={2.3}
            is1155={true}
            owned={44}
          />
        </div>
      </div>
    </div>
  );
};
